- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install python
  ansible.builtin.apt:
    name: "python"
    state: present
- name: Install nodejs
  ansible.builtin.apt:
    name: "nodejs"
    state: present
- name: Install npm
  ansible.builtin.apt:
    name: "npm"
    state: present
